modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU Lesser General Public v3"
issueTrackerURL="http://my.issue.tracker/" #optional TODO

[[mods]] #mandatory
modId="undeco" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ornamental: Unusually Decorative" #mandatory
updateJSONURL="http://myurl.me/" #optional TODO
displayURL="https://www.curseforge.com/minecraft/mc-mods/ornamental-unusually-decorative"
authors="Androsa" #optional
description='''
The simple things in life, now made more simple.
Ornamental: Unusually Decorative is the child of the original Ornamental mod. The difference: Undeco is designed to cover simple or basic materials, rather than the weird materials.
See new materials such as Logs, Stone, Planks, and anything else that you might not know that you want, but this time it's something you expect to use.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.undeco]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.undeco]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.undeco]]
    modId="ornamental"
    mandatory=true
    versionRange="[4.4]"
    ordering="NONE"
    side="BOTH"
